# constants.py
BOARD_SIZE = 9
CELL_SIZE = 65
BOARD_PADDING = 40
WINDOW_WIDTH = BOARD_PADDING * 2 + BOARD_SIZE * CELL_SIZE 
WINDOW_HEIGHT = BOARD_PADDING * 2 + BOARD_SIZE * CELL_SIZE + 120

EMPTY = '.'
PLAYER_X = 'X'
AI_O = 'O'

MAX_DEPTH = 2
WIN_COUNT = 4